export const RESERVA_STATUS = {
  PENDIENTE: 'PENDIENTE',
  CONFIRMADA: 'CONFIRMADA',
  CANCELADA: 'CANCELADA',
  COMPLETADA: 'COMPLETADA',
  FALLIDA_PROVEEDOR: 'FALLIDA_PROVEEDOR',
  FALLIDA_PAGO: 'FALLIDA_PAGO',
  FALLIDA_FACTURACION: 'FALLIDA_FACTURACION',
  FALLIDA_CONFIRMACION: 'FALLIDA_CONFIRMACION',
} as const;

export type ReservaStatus = (typeof RESERVA_STATUS)[keyof typeof RESERVA_STATUS];
